name: shaders_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.2
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  shaders:
     - shaders/sphere_torus.frag
     - shaders/red.frag
  # uses-material-design: true
